storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
    maxage: 10m
    timeout: 30s

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

log:
  - {type: stdout, format: pretty, level: http}

middlewares:
  audit:
    enabled: true

listen:
  - 0.0.0.0:4873

server:
  keepAliveTimeout: 60

max_body_size: 100mb
